config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :products
  get '/', to: 'login#index'
  post '/login', to: 'login#logging'
  post '/logout', to: 'logout#logout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord

  validates :name, :password_hash, presence: true
  VALIDATE_EMAIL = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, format: { with: VALIDATE_EMAIL}, uniqueness: {case_sensitive: false}, presence: true
  before_save do
    self.password_hash = BCrypt::Password.create(password_hash)
  end
  before_save do
    self.email = email.downcase
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image

  validates :code, uniqueness: true, presence: true
  validates :name, :quantity, :brand, :manufactured_at, :price, :cost_price, presence: true
  
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[show edit update destroy]
  before_action :current_admin?, only: %i[destroy]
  
  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show; end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit;

  end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)
    
    respond_to do |format|
      if @administrator.save
        format.html { redirect_to administrator_url(@administrator), notice: 'Administrador cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrator_url(@administrator), notice: 'Administrador atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrador excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_administrator
    @administrator = Administrator.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def administrator_params
    params.require(:administrator).permit(:name, :email, :password_hash)
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :validate_login

  def validate_login
    if cookies[:crud_sopha].present?
      admin = JSON.parse(cookies[:crud_sopha])
      if admin['id'].present?
        administrators = Administrator.where(id: admin['id'])
        if administrators.count > 0
          @administrator = administrators.first
          return
        end
      end
    end
    redirect_to '/'
  end
  
  def current_admin?
    admin = JSON.parse(cookies[:crud_sopha])
    if @administrator.id == admin['id'].to_i
      redirect_to administrators_url, alert: 'Não é possível deletar administrador logado!'
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :validate_login
  def index; end

  def logging 
    administrator = Administrator.where(email: params[:email]).first
    if(administrator.present? && BCrypt::Password.new(administrator.password_hash) == params[:password_hash]) 
      expire = 24.hours.from_now
      value = {
        id: administrator.id,
        name: administrator.name,
        email: administrator.email
      }
      cookies[:crud_sopha] = { value: value.to_json, expires: expire, httponly: true }

      redirect_to '/products'
    else
      redirect_to '/', alert: 'Email ou senha inválidos'
    end
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  def logout
    cookies[:crud_sopha] = nil
    redirect_to '/'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Produto cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :code, :quantity, :brand, :manufactured_at, :due_date, :price, :cost_price, :image)
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p>
    <strong>Nome:</strong>
    <%= administrator.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= administrator.email %>
  </p>

</div>

app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div style="color: red">
      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nome", style: "display: block" %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :email, "Email", style: "display: block" %>
    <%= form.text_field :email, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :password_hash, "Senha", style: "display: block" %>
    <%= form.text_field :password_hash, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mt-3">

    <% if params["action"] == "edit"%> 
    <%=form.submit "Alterar", class: "btn btn-success btn-lg" %>
    <% else %>
    <%=form.submit "Cadastrar", class: "btn btn-success btn-lg" %>
    <% end %>
    <%= link_to "Voltar", administrators_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<div class="col-lg-8 mx-auto mt-3 mb-3">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Editar administrador</h1>
    </div>
    <div class="card-body">
      <%@administrator.password_hash = ""%>
     <%= render "form", administrator: @administrator %>
    </div>
  </div>  
</div>

app/views/administrators/index.html.erb
<p style="color: green"><%= notice %></p>
<%if alert %>
  <p style="color: red"><%= alert %></p>
<%end%>
<div id="administrators">
<h1>Administradores</h1>
  <table class="table table-responsive shadow table-hover text-center">
          <thead class="thead table-dark">
              <tr role="row">
                <th>Nome</th>
                <th>E-mail</th>
                <th>Ações</th>
              </tr>
          </thead>
          
          <tbody>
          <% @administrators.each do |administrator| %>
            <tr>
              <td><%= administrator.name %></td>
              <td><%= administrator.email %></td>
              <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                  <%= link_to "Detalhes", administrator, class: "btn btn-sm btn-secondary"%>
                  <%= link_to "Editar", edit_administrator_path(administrator), class: "btn btn-sm btn-primary" %>
                  
                  <%if @administrator.id != administrator.id%>
                  <%= button_to "Deletar", administrator, method: :delete, class: "btn btn-sm btn-danger" %>
                  <%else%>
                  <%= button_to "Deletar", administrator, method: :delete, class: "btn btn-sm btn-danger disabled" %>
                  <%end%>  
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
  </table>
  <%= link_to "Cadastrar novo", new_administrator_path, class: "btn btn-lg btn-success" %>
</div>

app/views/administrators/new.html.erb
<div class="col-lg-8 mx-auto mt-3 mb-3">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Novo Administardor</h1>
    </div>
    <div class="card-body">
      <%= render "form", administrator: @administrator %>
    </div>
  </div>  
</div>

app/views/administrators/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-8 mx-auto mt-3 mb-3">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Detalhes</h1>
    </div>
    <div class="card-body">
      <%= render @administrator %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
      <%= link_to "Voltar", administrators_path, class: "btn btn-primary btn-lg" %>
      <%admin = JSON.parse(cookies[:crud_sopha])%>
      <%if @administrator.id != admin['id'].to_i%>
        <%= button_to "Deletar", @administrator, method: :delete, class: "btn btn-lg btn-outline-danger" %> 
      <%else%>
        <%= button_to "Deletar", @administrator, method: :delete, class: "btn btn-lg btn-outline-danger disabled" %>
      <%end%>  
      
      </div>
    </div>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudSopha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  
  <body class="">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container col-lg-9">
      <a class="navbar-brand" href="/products">CRUD-SOPHA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a <% if params["controller"] == "products" %> class="nav-link active" <% else %>class="nav-link" <% end %> href="/products">Produtos</a>
          <a <% if params["controller"] == "administrators" %> class="nav-link active" <% else %>class="nav-link" <% end %> href="/administrators">Administradores</a>
        </div>
        
      </div>
      <div class="text-white justify-content-end me-2">
          <p class="text-white nav">Bem vindo, <%=@administrator.name%></p>
      </div>
      <form class="d-flex" action="/logout" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>  
        <button class="btn btn-outline-success btn-lg" type="submit">Sair</button>
      </form>
    </div>
  </nav>
  <div class="container col-lg-9">
    <div class="row">
         <%= yield %>   
    </div>
  </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudSopha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <div class="row">
         <%= yield %>   
    </div>
  </div>
  </body>
</html>

app/views/login/index.html.erb
<div class="col-lg-8 mx-auto mt-5">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Sopha Produtos</h1>
    </div>
    <div class="card-body">
      <form method="post" action="/login/" class="form-signin">

        <div class="form-group mb-3">
          <label for="email" class="sr-only">Email</label>
          <input type="email" id="email" name="email" class="form-control" placeholder="Email" required="" autofocus="">
        </div>
          
        <div class="form-group mb-3">
          <label for="password" class="sr-only">Senha</label>
          <input type="password" id="password" name="password_hash" class="form-control" placeholder="Senha" required="">
        </div> 
        <%if alert %>
          <p style="color: red"><%= alert %></p>
        <%end%>

        <div class="form-group mb-3">
          <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        </div>  
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </form>
    </div>
  </div>  
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group mb-3">
      <%= form.label :name, "Nome", style: "display: block" %>
      <%= form.text_field :name, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :code, "Código", style: "display: block" %>
      <%= form.number_field :code, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :quantity, "Quantidade", style: "display: block" %>
      <%= form.number_field :quantity, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :brand, "Marca", style: "display: block" %>
      <%= form.text_field :brand, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :manufactured_at, "Data de Fabricação", style: "display: block" %>
      <%= form.date_field :manufactured_at, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :due_date, "Vencimento", style: "display: block" %>
      <%= form.date_field :due_date, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :price, "Preço", style: "display: block" %>
      <%= form.text_field :price, class: "form-control form-control-lg" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :cost_price, "Preço de custo", style: "display: block" %>
      <%= form.text_field :cost_price, class: "form-control form-control-lg"  %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :image, "Imagem", style: "display: block" %>
      <%= form.file_field :image, class: "form-control form-control-lg"  %>
    </div>

    <div class="form-group mt-3">

      <% if params["action"] == "edit"%> 
      <%=form.submit "Alterar", class: "btn btn-success btn-lg" %>
      <% else %>
      <%=form.submit "Cadastrar", class: "btn btn-success btn-lg" %>
      <% end %>
      <%= link_to "Voltar", products_path, class: "btn btn-outline-primary btn-lg" %>
    </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Nome:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Código:</strong>
    <%= product.code %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= product.quantity %>
  </p>

  <p>
    <strong>Marca:</strong>
    <%= product.brand %>
  </p>

  <p>
    <strong>Data de fabricação:</strong>
    <%= product.manufactured_at.strftime('%d/%m/%Y') %>
  </p>

  <p>
    <strong>Vencimento:</strong>
    <%= product.due_date %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Preço de custo:</strong>
    <%= product.cost_price %>
  </p>
  <%if product.image.persisted?%>
    <p class="text-center">
      <%= image_tag product.image, class: "img-fluid"%>
    </p>
  <%end%>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="products">
<h1>Produtos</h1>
  <table class="table table-responsive shadow table-bordered no-footer table-hover text-center">
          <thead class="thead table-dark text-center">
              <tr role="row">
                <th>Nome</th>
                <th>Código</th>
                <th>Marca</th>
                <th>Data de fabricação</th>
                <th>Vencimento</th>
                <th>Preço</th>
                <th>Preço de custo</th>
                <th>Ações</th>
              </tr>
          </thead>
          
          <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.name %></td>
              <td><%= product.code %></td>          
              <td><%= product.brand %></td>   
              <td><%= product.manufactured_at.strftime('%d/%m/%Y') %></td>
              <td><%= product.due_date %></td>
              <td><%= product.price %></td>
              <td><%= product.cost_price %></td>
              <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                  <%= link_to "Detalhes", product, class: "btn btn-sm btn-secondary"%>
                  <%= link_to "Editar", edit_product_path(product), class: "btn btn-sm btn-primary" %>
                  <%= button_to "Deletar", product, method: :delete, class: "btn btn-sm btn-danger" %>  
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
  </table>
  <%= link_to "Cadastrar novo", new_product_path, class: "btn btn-lg btn-success" %>
</div>

app/views/products/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Novo Produto</h1>
    </div>
    <div class="card-body">
      <%= render "form", product: @product %>
    </div>
  </div>  
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-8 mx-auto mt-3 mb-3">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">Detalhes</h1>
    </div>
    <div class="card-body">
      <%= render @product %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-center">
      <%= link_to "Voltar", products_path, class: "btn btn-primary btn-lg" %>
      <%= button_to "Deletar", @product, method: :delete, class: "btn btn-lg btn-outline-danger" %> 
      </div>
    </div>
  </div>  
</div>